substitutions:
  screensaver: 30 sec # Timeout for how long the screen should stay on after the last interaction

esphome:
    on_boot:
        - priority: -100
          then:
            - delay: 2s        # optional, wait for init/network
            - light.turn_on:
                id: back_light
                brightness: 50%
            - script.execute: screentime

external_components:
  - source:
      type: git
      url: https://github.com/donnyb999/WaveShare-Knob-Esp32S3/
    components: [rotary_encoder_custom]

display:
  - platform: mipi_spi
    id: main_display
    model: JC3636W518V2
    rotation: 0
    cs_pin: 14
    reset_pin: 21
    update_interval: 1s

binary_sensor:
  - platform: template
    name: "Touch Button"
    id: touch_input

# Touchscreen (CST816S)
touchscreen:
  - platform: cst816
    id: my_touchscreen
    display: main_display
    reset_pin: 10  # TOUCH_PIN_NUM_RST
    interrupt_pin: 9   # TOUCH_PIN_NUM_INT
    transform:
      mirror_x: false
      mirror_y: false
      swap_xy: false
    on_touch:
      then:
        - logger.log:
            format: "Touch at (%d, %d)"
            args: [touch.x, touch.y]
        - binary_sensor.template.publish:
            id: touch_input
            state: ON
        - script.execute: screentime
        - lambda: |-
            // Determine which element was touched based on Y coordinate
            // Element positions: 60, 120, 180, 240, 300, 360 (y positions)
            int y = touch.y;
            int element = -1;
            
            if (y >= 60 && y < 110) element = 0;  // Power
            else if (y >= 120 && y < 170) element = 1;  // Temperature
            else if (y >= 180 && y < 230) element = 2;  // Steam
            else if (y >= 240 && y < 290) element = 3;  // PreBrew
            else if (y >= 300 && y < 350) element = 4;  // PreInfusion
            else if (y >= 360 && y < 410) element = 5;  // Brewing
            
            if (element >= 0) {
              id(select_element).execute(element);
            }
    on_release:
      then:
        - binary_sensor.template.publish:
            id: touch_input
            state: OFF

# SPI configuration for the display
spi:
  id: display_qspi
  type: quad
  clk_pin: 13
  data_pins: [15, 16, 17, 18]   # TFT_SDA0..3
  
# I2C for touch controller
i2c:
  sda: 11  # TOUCH_PIN_NUM_I2C_SDA
  scl: 12  # TOUCH_PIN_NUM_I2C_SCL
  scan: true
  id: ic_bus

output:
  - platform: ledc
    pin: GPIO47      # your backlight GPIO
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: back_light
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms
    on_turn_off: 
      then:
        - lvgl.pause:
            show_snow: true
    on_turn_on: 
      then:
        - lvgl.resume:
    
script:    
  - id: screentime
    mode: restart
    then:
      - light.turn_on: back_light
      - delay: $screensaver
      - light.turn_off: back_light
      
  - id: screenoff
    then:
      - script.stop: screentime
      - light.turn_off: back_light

